Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'