default: &default
  adapter: postgresql
  encoding: unicode
  host: dice-db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test